/// Flutter icons PhysicsAppIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PhysicsAppIcons
///      fonts:
///       - asset: fonts/PhysicsAppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PhysicsAppIcons {
  PhysicsAppIcons._();

  static const _kFontFam = 'PhysicsAppIcons';
  static const String? _kFontPkg = null;

  static const IconData simulation = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData charts = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData process = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData parameters = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
